Traceback (most recent call last):
  File "/Users/pcchen/myvenv/lib/python3.13/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/Users/pcchen/myvenv/lib/python3.13/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/pcchen/myvenv/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/Users/pcchen/myvenv/lib/python3.13/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "/Users/pcchen/myvenv/lib/python3.13/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/pcchen/myvenv/lib/python3.13/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from qiskit_ibm_runtime import QiskitRuntimeService
 
service = QiskitRuntimeService(channel="ibm_quantum", token="e8f013945d62820c91250afae31a8c9469fe92b2de6bab1475bee313903785d6373bed9ce8563b1f3b745f3b2685f9d51691c47daa075e306d94da2cd1f8fdd2")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mqiskit_ibm_runtime[39;00m [38;5;28;01mimport[39;00m QiskitRuntimeService
[1;32m      3[0m service [38;5;241m=[39m QiskitRuntimeService(channel[38;5;241m=[39m[38;5;124m"[39m[38;5;124mibm_quantum[39m[38;5;124m"[39m, token[38;5;241m=[39m[38;5;124m"[39m[38;5;124me8f013945d62820c91250afae31a8c9469fe92b2de6bab1475bee313903785d6373bed9ce8563b1f3b745f3b2685f9d51691c47daa075e306d94da2cd1f8fdd2[39m[38;5;124m"[39m)

[0;31mModuleNotFoundError[0m: No module named 'qiskit_ibm_runtime'

